# Generated by Django 5.2.6 on 2025-09-16 18:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('pakaian', 'Pakaian'), ('aksesoris', 'Aksesoris'), ('alat pijat pria', 'Alat Pijat Pria'), ('perlengkapan olahraga', 'Perlengkapan Olahraga')], default='aksesoris', max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
