# Generated by Django 5.2.6 on 2025-09-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('pakaian', 'Pakaian'), ('aksesoris', 'Aksesoris'), ('alat pijat pria', 'Alat Pijat Pria'), ('perlengkapan olahraga', 'Perlengkapan Olahraga')], default='aksesoris', max_length=30),
        ),
    ]
