# Generated by Django 5.2.6 on 2025-09-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('pakaian', 'Pakaian'), ('aksesoris', 'Aksesoris'), ('merchandise', 'Merchandise'), ('perlengkapan olahraga', 'Perlengkapan Olahraga')], default='aksesoris', max_length=30),
        ),
    ]
