# Generated by Django 5.2.6 on 2025-09-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sportsware', 'Sportsware'), ('accessories', 'Accessories'), ('merchandise', 'Merchandise'), ('jersey', 'Jersey'), ('shoes', 'Shoes')], default='aksesoris', max_length=30),
        ),
    ]
